apiVersion: v1
kind: Service
metadata:
  name: sargam-payment-service
spec:
  selector:
    app: sargam-payment
  ports:
  - protocol: "TCP"
    port: 8282
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sargam-payment
spec:
  selector:
    matchLabels:
      app: sargam-payment
  replicas: 4
  template:
    metadata:
      labels:
        app: sargam-payment
    spec:
      containers:
      - name: sargam-payment
        image: sargam-payment:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
